// Regenerate supabase/seeds/recipe_inputs_seed.sql from the client's recipe tables.
//
// The server's recipe_inputs table (craft_debit's source of truth) must mirror the client's craft
// bills exactly. This dumps __FF.buildRecipeManifest() from a headless load of index.html and writes
// the canonical seed. Run it after any recipe change, then re-run the seed in the Supabase SQL editor.
// CI runs it with --check to fail the build if the committed seed is stale (see tests.yml).
//
//   node scripts/dump-recipes.mjs           # rewrite the seed
//   node scripts/dump-recipes.mjs --check   # exit 1 if the committed seed differs from a fresh dump
//
// Uses the same puppeteer harness as tests/run-unit.mjs (Chromium bundled in tests/node_modules).
import http from 'node:http';
import { readFile, writeFile } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SEED = join(ROOT, 'supabase', 'seeds', 'recipe_inputs_seed.sql');
const MIME = { '.html': 'text/html', '.js': 'application/javascript', '.css': 'text/css', '.json': 'application/json', '.svg': 'image/svg+xml' };
// puppeteer is a devDependency of tests/, not the repo root.
const require = createRequire(join(ROOT, 'tests', 'package.json'));
const puppeteer = require('puppeteer');

// Build the seed SQL from the manifest -- MUST stay byte-identical to the in-browser generator so the
// CI --check diff is meaningful. Keys are [A-Za-z0-9_:] but escape defensively anyway.
function seedSql(manifest) {
  const esc = (s) => String(s).replace(/'/g, "''");
  const rows = [];
  for (const rk of Object.keys(manifest).sort()) {
    const bill = manifest[rk];
    for (const ik of Object.keys(bill).sort()) rows.push(`('${esc(rk)}','${esc(ik)}',${Math.floor(bill[ik])})`);
  }
  return '-- GENERATED by buildRecipeManifest() -- DO NOT EDIT BY HAND. Regenerate via scripts/dump-recipes.\n'
    + `-- Server-canonical craft input bills (Stage A3). ${Object.keys(manifest).length} recipes, ${rows.length} rows.\n`
    + 'begin;\n'
    + 'truncate table public.recipe_inputs;\n'
    + 'insert into public.recipe_inputs (recipe_key, item_key, qty) values\n'
    + rows.join(',\n') + ';\n'
    + 'commit;\n';
}

const server = http.createServer(async (req, res) => {
  try {
    let p = decodeURIComponent((req.url || '/').split('?')[0]);
    if (p === '/') p = '/index.html';
    const file = normalize(join(ROOT, p));
    if (!file.startsWith(normalize(ROOT))) { res.statusCode = 403; return res.end('forbidden'); }
    res.setHeader('Content-Type', MIME[extname(file).toLowerCase()] || 'application/octet-stream');
    res.end(await readFile(file));
  } catch { res.statusCode = 404; res.end('not found'); }
});
await new Promise((r) => server.listen(0, r));
const port = server.address().port;

const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
let exitCode = 0;
try {
  const page = await browser.newPage();
  page.on('pageerror', (e) => console.log('PAGEERROR:', e.message));
  await page.goto(`http://localhost:${port}/index.html?selftest`, { waitUntil: 'domcontentloaded', timeout: 30000 });
  await page.waitForFunction('window.__FF && typeof window.__FF.buildRecipeManifest === "function"', { timeout: 30000 });
  const manifest = await page.evaluate(() => window.__FF.buildRecipeManifest());
  const sql = seedSql(manifest);
  const check = process.argv.includes('--check');
  if (check) {
    let current = '';
    try { current = await readFile(SEED, 'utf8'); } catch {}
    if (current.replace(/\r\n/g, '\n') !== sql) {
      console.error('recipe_inputs seed is STALE. Run `node scripts/dump-recipes.mjs` and commit + re-run the seed SQL.');
      exitCode = 1;
    } else {
      console.log(`recipe_inputs seed is up to date (${Object.keys(manifest).length} recipes).`);
    }
  } else {
    await writeFile(SEED, sql);
    console.log(`Wrote ${SEED} (${Object.keys(manifest).length} recipes).`);
  }
} catch (e) {
  console.error('dump-recipes error:', e.message); exitCode = 1;
} finally {
  await browser.close();
  server.close();
}
process.exit(exitCode);
